gloo:
  xdsBindAddr: 0.0.0.0:9977
metadata:
  name: default
  namespace: gloo-system
devMode: true
discoveryNamespace: gloo-system
directoryArtifactSource:
  directory: /data/artifact
directoryConfigSource:
  directory: /data/config
directorySecretSource:
  directory: /data/secret
refreshRate: 5s
watchNamespaces:
- gloo-system
gateway:
  persistProxySpec: true

