changelog:
  - type: NON_USER_FACING
    issueLink: https://github.com/solo-io/gloo/issues/2534
    resolvesIssue: false
    description: >
      Expose a new Gateway option, in the Settings API: isolate_virtual_hosts_by_ssl_config.
      If set, group virtual hosts by matching ssl config, and isolate them on separate filter chains
      The default behavior is to aggregate all virtual hosts, and expose them on identical filter chains,
      each with a FilterChainMatch that corresponds to the ssl config.
      Individual Gateways can override this behavior by configuring the "gateway.solo.io/isolate_vhost" annotation
      to be a truthy ("true", "false") value
  - type: DEPENDENCY_BUMP
    dependencyOwner: solo-io
    dependencyRepo: protoc-gen-openapi
    dependencyTag: v0.1.0
  - type: DEPENDENCY_BUMP
    dependencyOwner: solo-io
    dependencyRepo: solo-kit
    dependencyTag: v0.29.1