name: Test Flake
description: Track non-deterministic test behavior
labels: ["Type: Bug", "Type: CI Test Flake"]
body:
  - type: textarea
    id: failing-tests
    attributes:
      label: Which tests failed?
      placeholder: |
                   Include the test name/description and error to make this issue easier to find in searches.
                   Check whether an issue already exists for the same failure
    validations:
      required: true
  - type: textarea
    id: initial-investigation
    attributes:
      label: Initial Investigation
      placeholder: |
        Does this look like test pollution? Resources not fully ready?
        Ideally you should spend a few minutes trying to track down the cause of the flake.
    validations:
      required: false
  - type: textarea
    id: Additional Information
    attributes:
      label: Additional Information
      placeholder: |
        Include links to full logs of failed runs, etc.
    validations:
      required: false
