version: '3'

services:
  gloo:
    image: ${GLOO_REPO:-quay.io/solo-io}/gloo:${GLOO_VERSION:-1.14.0-beta1}
    working_dir: /
    command:
    - "--dir=/data/"
    volumes:
    - ./data:/data/
    ports:
    - "9977:9977"
    - "10010:10010" # port exposed by `settings.devMode=true`
    restart: always

  gateway-proxy:
    image: ${GLOO_REPO:-quay.io/solo-io}/gloo-envoy-wrapper:${GLOO_VERSION:-1.14.0-beta1}
    entrypoint: ["envoy"]
    command: ["-c", "/config/envoy.yaml", "--disable-hot-restart"]
    volumes:
    - ./data/envoy-config.yaml:/config/envoy.yaml:ro
    ports:
    - "8080:8080"
    - "8443:8443"
    - "19000:19000"
    restart: always

 # example application, the swagger petstore
  petstore:
    image: ${PETSTORE_REPO:-quay.io/solo-io}/petstore:v1
    ports:
    - "8090:8080"
    restart: always
