name: Gloo Istio Regression Tests

description: Tests which run Gloo Edge in a Kubernetes cluster with Istio

runs:
  using: "composite"
  steps:
    - name: Prep Go Runner
      uses: ./.github/workflows/composite-actions/prep-go-runner
    - name: Install kind
      uses: helm/kind-action@v1.5.0
      with:
        install_only: true
        version: ${{ matrix.kube-version.kind }}
    - uses: azure/setup-kubectl@v3
      id: kubectl
      with:
        version: ${{ matrix.kube-version.kubectl }}
    - uses: azure/setup-helm@v3
      with:
        version: ${{ matrix.kube-version.helm }}
    - name: Setup test env
      shell: bash
      env:
        KUBE2E_TESTS: istio
        CLUSTER_NAME: 'kind'
        CLUSTER_NODE_VERSION: ${{ matrix.kube-version.node }}
      run: ./ci/kind/setup-kind.sh
    - name: Testing - kube e2e regression tests
      env:
        KUBE2E_TESTS: istio
      shell: bash
      run: |
        if [[ "${{ matrix.kube-e2e-test-type }}" == "gloo-gateway" ]]; then
          export GLOO_GATEWAY_SETUP=true
        elif [[ "${{ matrix.kube-e2e-test-type }}" == "istio-auto" ]]; then
          export ISTIO_AUTO_MTLS=true
        fi
        make install-test-tools run-kube-e2e-tests
    - name: save results
      if: ${{ failure() }}
      shell: bash
      run: mkdir -p _output/kube2e-artifacts && echo '{"url":"https://github.com/solo-io/gloo/actions/runs/${{github.run_id}}",
        "name":"${{matrix.kube-e2e-test-type}}@k8s${{matrix.kube-version.kubectl}}"}' > _output/kube2e-artifacts/test-out.json
    - uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: ${{matrix.kube-e2e-test-type}}@k8s${{matrix.kube-version.kubectl}}-kube-dump
        path: "_output/kube2e-artifacts"
        if-no-files-found: warn