name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2
      - name: Check for DO_NOT_SUBMIT
        run: ./ci/do-not-submit.sh ${{ steps.changed-files.outputs.all_modified_files }}
